"""Shared paths and the games/ index writers (manifest.json, PROGRESS.md)."""

from __future__ import annotations

import json
import os
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
GAMES = ROOT / "games"
STOCKFISH = ROOT / "backend" / "tools" / "stockfish" / "stockfish" / "stockfish-windows-x86-64-universal.exe"
ENGINE = ROOT / "backend" / "engine" / "target" / "release" / "chezz.exe"
PROGRESS = ROOT / "PROGRESS.md"

# 1320-1500 were the warm-up; after that the ladder jumps to 2500 and climbs in 200-Elo steps
# (the prize is the highest win, and 3190 is Stockfish's maximum UCI_Elo).
LADDER = [1320, 1400, 1500, 2500, 2700, 2900, 3100, 3190]


def git_commit() -> str:
    try:
        sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                             capture_output=True, text=True, check=True).stdout.strip()
        dirty = subprocess.run(["git", "status", "--porcelain", "backend/engine/src"], cwd=ROOT,
                               capture_output=True, text=True).stdout.strip()
        return sha + ("-dirty" if dirty else "")
    except Exception:
        return "unknown"


def load_games() -> list[dict]:
    games = []
    for p in sorted(GAMES.glob("[0-9][0-9][0-9][0-9]_*.json")):
        rec = json.loads(p.read_text(encoding="utf-8"))
        rec["_file"] = p.name
        games.append(rec)
    return games


def next_game_id() -> str:
    """Each machine owns a 1000-id window via CHEZZ_ID_BASE (0 = machine A, 1000 = machine B, ...),
    so two machines playing in parallel can never collide on filenames."""
    base = int(os.environ.get("CHEZZ_ID_BASE", "0"))
    ids = [int(p.name[:4]) for p in GAMES.glob("[0-9][0-9][0-9][0-9]_*.json")]
    mine = [i for i in ids if base < i <= base + 999]
    return f"{max(mine, default=base) + 1:04d}"


def highest_win(games: list[dict]) -> int | None:
    wins = [g["stockfishElo"] for g in games if g["winner"] == "us"]
    return max(wins) if wins else None


def next_ladder_elo(games: list[dict]) -> int:
    best = highest_win(games)
    if best is None:
        return LADDER[0]
    higher = [e for e in LADDER if e > best]
    return higher[0] if higher else LADDER[-1]


def our_max_ms(game: dict) -> int:
    return max((m["timeMs"] for m in game["moves"] if m["by"] == "us"), default=0)


def write_indexes() -> None:
    """Regenerate manifest.json and PROGRESS.md from the per-game files (single writer, never hand-edit)."""
    games = load_games()
    entries = []
    for g in games:
        analysis = g["_file"].replace(".json", ".analysis.md")
        entries.append({
            "id": g["id"],
            "file": g["_file"],
            "analysis": analysis if (GAMES / analysis).exists() else None,
            "date": g["date"],
            "stockfishElo": g["stockfishElo"],
            "ourColor": g["ourColor"],
            "result": g["result"],
            "winner": g["winner"],
            "termination": g["termination"],
            "plies": len(g["moves"]),
            "engineVersion": g["engine"]["version"],
            "ourMaxMoveMs": our_max_ms(g),
        })
    manifest = {
        "highestWin": highest_win(games),
        "nextElo": next_ladder_elo(games),
        "ladder": LADDER,
        "games": entries,
    }
    GAMES.mkdir(exist_ok=True)
    (GAMES / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Ladder progress",
        "",
        "Auto-generated by `backend/runner.py` from `games/` — do not edit by hand.",
        "",
        f"- **Highest Stockfish Elo beaten:** {manifest['highestWin'] or '—'}",
        f"- **Next ladder Elo:** {manifest['nextElo']}",
        f"- **Games played:** {len(games)} "
        f"(W {sum(g['winner'] == 'us' for g in games)} / "
        f"D {sum(g['winner'] == 'draw' for g in games)} / "
        f"L {sum(g['winner'] == 'stockfish' for g in games)})",
        f"- **Slowest move by our engine, all games:** {max((e['ourMaxMoveMs'] for e in entries), default=0)} ms "
        f"(limit 5000 ms; engine caps itself at 4750 ms)",
        "",
        "| # | Date (UTC) | Stockfish Elo | Our color | Result | Outcome | Termination | Plies | Our max think | Engine | Game | Analysis |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for e, g in zip(entries, games):
        outcome = {"us": "**WIN**", "draw": "draw", "stockfish": "loss"}[e["winner"]]
        analysis = f"[md](games/{e['analysis']})" if e["analysis"] else "—"
        lines.append(
            f"| {e['id']} | {e['date'][:16].replace('T', ' ')} | {e['stockfishElo']} | {e['ourColor']} | "
            f"{e['result']} | {outcome} | {e['termination']} | {e['plies']} | {e['ourMaxMoveMs']} ms | "
            f"{g['engine']['version']} ({g['engine'].get('commit', '?')}) | [json](games/{e['file']}) | {analysis} |"
        )
    PROGRESS.write_text("\n".join(lines) + "\n", encoding="utf-8")
